In [26]:
import pandas as pd
import numpy as np

In [43]:
data = pd.read_csv('data.csv')

C:\Users\prasa\AppData\Local\Temp\ipykernel_13476\2471439888.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('data.csv')

In [44]:
data.head()

,Picture,Website,City,County,Country,Organization Name,Individual Name,Role,Name of Firm,Firm Data Logo,Funding Stage,Industry Focus,Type,Email Id,Phone Number,LinkedIn Profile URL,Facebook Profile URL,Twitter Profile URL,Source of Data
0,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,www.fjlabs.com,New York,New York,United States,FJ Labs,NaN,Organization,NaN,NaN,Seed | Series A | Series B,AI | E-Commerce | Marketplaces | Retail | Real...,Micro VC | Venture Capital,NaN,(415) 769-9219,https://www.linkedin.com/company/fj-labs,https://www.facebook.com/FJLABS,https://www.twitter.com/FjLabs,raizer.app
1,https://xubs-akpz-sxip.n7.xano.io/vault/JXk4kD...,NaN,San Mateo,California,United States,NaN,Anupam Rastogi,Managing Partner,Emergent Ventures,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,Pre-seed,AI | Machine Learning | FinTech | Lending and ...,Angel Group | Private Equity Firm,anupam@emergent.vc,NaN,https://www.linkedin.com/in/anupamr,NaN,NaN,raizer.app
2,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,www.indexventures.com,San Francisco,California,United States,Index Ventures,NaN,Organization,NaN,NaN,Seed | Series A | Series B,AI | E-Commerce | Fashion | Retail | Enterpris...,Venture Capital,press@indexventures.com,415-471-1700,http://www.linkedin.com/company/index-ventures,https://www.facebook.com/profile.php?id=100075...,http://twitter.com/indexventures,raizer.app
3,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,www.a16z.com,Menlo Park,California,United States,Andreessen Horowitz,NaN,Organization,NaN,NaN,Series A | Series B | Seed,AI | eGames | Cloud Infrastructure | Enterpris...,Venture Capital,businessplans@a16z.com,(650) 798-5800,https://www.linkedin.com/company/a16z,https://www.facebook.com/andreessenhorowitz,https://www.twitter.com/a16z,raizer.app
4,https://xubs-akpz-sxip.n7.xano.io/vault/JXk4kD...,shine.vc,New York,New York,United States,NaN,Mo Koyfman,General Partner,Shine Capital,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,Series A | Seed,AI | Manufacturing | FinTech | Payments | Web ...,Venture Capital,mo@shine.vc,NaN,https://www.linkedin.com/in/mokoyfman/,NaN,https://twitter.com/mokoyfman,raizer.app

In [45]:
data.describe()

,Picture,Website,City,County,Country,Organization Name,Individual Name,Role,Name of Firm,Firm Data Logo,Funding Stage,Industry Focus,Type,Email Id,Phone Number,LinkedIn Profile URL,Facebook Profile URL,Twitter Profile URL,Source of Data
count,35683,90274,123601,101031,147777,46194,102995,149189,45316,43730,129300,128246,149189,45958,26749,116817,16971,29248,149189
unique,22652,31676,4817,909,171,28937,63549,20,8750,8289,541,36418,431,28776,16029,73796,10768,18546,1
top,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,www.harbourvest.com,New York,California,United States,Eight Capital,Brian Kelly,Angel Investor,HarbourVest Partners,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,Seed,FinTech,Angel Investor,Paulgregory0000@gmail.com,9.20E+11,https://www.linkedin.com/company/startupbootcamp,http://www.facebook.com/,http://twitter.com/lainetom,raizer.app
freq,7,276,11444,17410,62483,9,13,57679,274,274,28037,1000,57679,37,131,14,12,7,149189

In [46]:
data.head(15)

,Picture,Website,City,County,Country,Organization Name,Individual Name,Role,Name of Firm,Firm Data Logo,Funding Stage,Industry Focus,Type,Email Id,Phone Number,LinkedIn Profile URL,Facebook Profile URL,Twitter Profile URL,Source of Data
0,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,www.fjlabs.com,New York,New York,United States,FJ Labs,NaN,Organization,NaN,NaN,Seed | Series A | Series B,AI | E-Commerce | Marketplaces | Retail | Real...,Micro VC | Venture Capital,NaN,(415) 769-9219,https://www.linkedin.com/company/fj-labs,https://www.facebook.com/FJLABS,https://www.twitter.com/FjLabs,raizer.app
1,https://xubs-akpz-sxip.n7.xano.io/vault/JXk4kD...,NaN,San Mateo,California,United States,NaN,Anupam Rastogi,Managing Partner,Emergent Ventures,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,Pre-seed,AI | Machine Learning | FinTech | Lending and ...,Angel Group | Private Equity Firm,anupam@emergent.vc,NaN,https://www.linkedin.com/in/anupamr,NaN,NaN,raizer.app
2,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,www.indexventures.com,San Francisco,California,United States,Index Ventures,NaN,Organization,NaN,NaN,Seed | Series A | Series B,AI | E-Commerce | Fashion | Retail | Enterpris...,Venture Capital,press@indexventures.com,415-471-1700,http://www.linkedin.com/company/index-ventures,https://www.facebook.com/profile.php?id=100075...,http://twitter.com/indexventures,raizer.app
3,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,www.a16z.com,Menlo Park,California,United States,Andreessen Horowitz,NaN,Organization,NaN,NaN,Series A | Series B | Seed,AI | eGames | Cloud Infrastructure | Enterpris...,Venture Capital,businessplans@a16z.com,(650) 798-5800,https://www.linkedin.com/company/a16z,https://www.facebook.com/andreessenhorowitz,https://www.twitter.com/a16z,raizer.app
4,https://xubs-akpz-sxip.n7.xano.io/vault/JXk4kD...,shine.vc,New York,New York,United States,NaN,Mo Koyfman,General Partner,Shine Capital,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,Series A | Seed,AI | Manufacturing | FinTech | Payments | Web ...,Venture Capital,mo@shine.vc,NaN,https://www.linkedin.com/in/mokoyfman/,NaN,https://twitter.com/mokoyfman,raizer.app
5,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,www.mesoncapital.com,San Francisco,California,United States,Meson Capital,NaN,Organization,NaN,NaN,Series A | Series C,Electric Vehicle | Manufacturing | Clean Tech ...,Hedge Fund,info@mesoncapital.com,1 415 322 0486,https://www.linkedin.com/company/meson-capital...,NaN,NaN,raizer.app
6,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,www.artsfund.org/,Seattle,Washington,United States,ArtsFund,NaN,Organization,NaN,NaN,Grant,Art | Music | Education | Hospitality | Entert...,Accelerator / Incubator,info@artsfund.org,206.281.9050,https://www.linkedin.com/company/artsfund/,https://www.facebook.com/pg/ArtsFundSeattle/,https://twitter.com/ArtsFund,raizer.app
7,https://xubs-akpz-sxip.n7.xano.io/vault/JXk4kD...,www.clear-sky.com/,North Palm Beach,Florida,United States,NaN,Patrick Heim,Managing Partner,ClearSky,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,Series C | Series A | Series B,AI | Clean and Renewable Energy | Energy | Ris...,Venture Capital,patrick.heim@clear-sky.com,NaN,https://www.linkedin.com/in/patrick-heim-57a45/,NaN,https://twitter.com/PatrickHeim,raizer.app
8,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,venturecatalysts.in,Mumbai,Maharashtra,India,Venture Catalysts,NaN,Organization,NaN,NaN,Seed,AI | Food and Beverage | Health Care | E-Comme...,Venture Capital | Accelerator / Incubator,info@venturecatalysts.in,022-28510071,https://www.linkedin.com/company/vcatsindia,https://www.facebook.com/vcatsindia,https://www.twitter.com/vcatsindia,raizer.app
9,https://xubs-akpz-sxip.n7.xano.io/vault/JXk4kD...,january.ventures,Boston,Massachusetts,United States,NaN,Jennifer Keiser Neundorfer,Investor,January Ventures,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,Series A | Seed | Pre-seed,AI | SaaS | Enterprise Software | Wellness | H...,Venture Capital,jennifer@january.ventures,NaN,https://www.linkedin.com/in/jkneundorfer,NaN,https://twitter.com/jkk?lang=en,raizer.app
10,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,www.8vc.com,San Francisco,California,United States,8VC,NaN,Organization,NaN,NaN,Series A | Seed | Series B,AI | Therapeutics | Data | Biotechnology | Mac...,Venture Capital,media@8vc.com,(415) 366-8422,https://www.linkedin.com/company/8vc,https://www.facebook.com/eightVC,https://twitter.com/8partners,raizer.app
11,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,www.foundersfund.com,San Francisco,California,United States,Founders Fund,NaN,Organization,NaN,NaN,Series A | Seed | Series B,AI | Biotechnology | Health Care | SaaS | Manu...,Venture Capital,NaN,1 415-359-1922,https://www.linkedin.com/company/the-founders-...,https://www.facebook.com/foundersfund,http://www.twitter.com/foundersfund,raizer.app
12,https://xubs-akpz-sxip.n7.xano.io/vault/JXk4kD...,www.initialized.com,San Francisco,California,United States,NaN,Parul Singh,Board Member,Initialized Capital,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,Series A | Seed,AI | Cloud Infrastructure | Enterprise Softwar...,Venture Capital,parul@initialized.com,NaN,https://www.linkedin.com/in/parulsingh,NaN,https://twitter.com/parulia,raizer.app
13,https://xubs-akpz-sxip.n7.xano.io/vault/JXk4kD...,launch.co,San Francisco,California,United States,NaN,Ashly WhiteHurst,Managing Partner,LAUNCH,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,Pre-seed | Seed,AI | HR Tech | Health Care | E-Commerce | SaaS...,Angel Group | Venture Capital | Accelerator / ...,ashley@launch.co,NaN,https://www.linkedin.com/in/awgallagher/,NaN,NaN,raizer.app
14,https://xubs-akpz-sxip.n7.xano.io/vault/JXk4kD...,www.multisig.ventures/,Singapore,Central Region,Singapore,NaN,Andrew Levenko,Associate,Multisig Ventures,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,Seed,FinTech | Web 3 | Crypto,Venture Capital,andrew.levenko@multisig.ventures,NaN,https://www.linkedin.com/in/andrew-levenko/,NaN,https://twitter.com/Lecrassus,raizer.app

In [48]:
data.head()

,Picture,Website,City,County,Country,Organization Name,Individual Name,Role,Name of Firm,Firm Data Logo,Funding Stage,Industry Focus,Type,Email Id,Phone Number,LinkedIn Profile URL,Facebook Profile URL,Twitter Profile URL,Source of Data
0,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,www.fjlabs.com,New York,New York,United States,FJ Labs,NaN,Organization,NaN,NaN,Seed | Series A | Series B,AI | E-Commerce | Marketplaces | Retail | Real...,Micro VC | Venture Capital,NaN,(415) 769-9219,https://www.linkedin.com/company/fj-labs,https://www.facebook.com/FJLABS,https://www.twitter.com/FjLabs,raizer.app
1,https://xubs-akpz-sxip.n7.xano.io/vault/JXk4kD...,NaN,San Mateo,California,United States,NaN,Anupam Rastogi,Managing Partner,Emergent Ventures,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,Pre-seed,AI | Machine Learning | FinTech | Lending and ...,Angel Group | Private Equity Firm,anupam@emergent.vc,NaN,https://www.linkedin.com/in/anupamr,NaN,NaN,raizer.app
2,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,www.indexventures.com,San Francisco,California,United States,Index Ventures,NaN,Organization,NaN,NaN,Seed | Series A | Series B,AI | E-Commerce | Fashion | Retail | Enterpris...,Venture Capital,press@indexventures.com,415-471-1700,http://www.linkedin.com/company/index-ventures,https://www.facebook.com/profile.php?id=100075...,http://twitter.com/indexventures,raizer.app
3,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,www.a16z.com,Menlo Park,California,United States,Andreessen Horowitz,NaN,Organization,NaN,NaN,Series A | Series B | Seed,AI | eGames | Cloud Infrastructure | Enterpris...,Venture Capital,businessplans@a16z.com,(650) 798-5800,https://www.linkedin.com/company/a16z,https://www.facebook.com/andreessenhorowitz,https://www.twitter.com/a16z,raizer.app
4,https://xubs-akpz-sxip.n7.xano.io/vault/JXk4kD...,shine.vc,New York,New York,United States,NaN,Mo Koyfman,General Partner,Shine Capital,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,Series A | Seed,AI | Manufacturing | FinTech | Payments | Web ...,Venture Capital,mo@shine.vc,NaN,https://www.linkedin.com/in/mokoyfman/,NaN,https://twitter.com/mokoyfman,raizer.app

In [54]:
copy_data = data.copy(deep=True)

In [55]:
copy_data.dropna(inplace=True, subset=['Individual Name'])

In [56]:
copy_data.head()

,Picture,Website,City,County,Country,Organization Name,Individual Name,Role,Name of Firm,Firm Data Logo,Funding Stage,Industry Focus,Type,Email Id,Phone Number,LinkedIn Profile URL,Facebook Profile URL,Twitter Profile URL,Source of Data
1,https://xubs-akpz-sxip.n7.xano.io/vault/JXk4kD...,NaN,San Mateo,California,United States,NaN,Anupam Rastogi,Managing Partner,Emergent Ventures,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,Pre-seed,AI | Machine Learning | FinTech | Lending and ...,Angel Group | Private Equity Firm,anupam@emergent.vc,NaN,https://www.linkedin.com/in/anupamr,NaN,NaN,raizer.app
4,https://xubs-akpz-sxip.n7.xano.io/vault/JXk4kD...,shine.vc,New York,New York,United States,NaN,Mo Koyfman,General Partner,Shine Capital,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,Series A | Seed,AI | Manufacturing | FinTech | Payments | Web ...,Venture Capital,mo@shine.vc,NaN,https://www.linkedin.com/in/mokoyfman/,NaN,https://twitter.com/mokoyfman,raizer.app
7,https://xubs-akpz-sxip.n7.xano.io/vault/JXk4kD...,www.clear-sky.com/,North Palm Beach,Florida,United States,NaN,Patrick Heim,Managing Partner,ClearSky,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,Series C | Series A | Series B,AI | Clean and Renewable Energy | Energy | Ris...,Venture Capital,patrick.heim@clear-sky.com,NaN,https://www.linkedin.com/in/patrick-heim-57a45/,NaN,https://twitter.com/PatrickHeim,raizer.app
9,https://xubs-akpz-sxip.n7.xano.io/vault/JXk4kD...,january.ventures,Boston,Massachusetts,United States,NaN,Jennifer Keiser Neundorfer,Investor,January Ventures,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,Series A | Seed | Pre-seed,AI | SaaS | Enterprise Software | Wellness | H...,Venture Capital,jennifer@january.ventures,NaN,https://www.linkedin.com/in/jkneundorfer,NaN,https://twitter.com/jkk?lang=en,raizer.app
12,https://xubs-akpz-sxip.n7.xano.io/vault/JXk4kD...,www.initialized.com,San Francisco,California,United States,NaN,Parul Singh,Board Member,Initialized Capital,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,Series A | Seed,AI | Cloud Infrastructure | Enterprise Softwar...,Venture Capital,parul@initialized.com,NaN,https://www.linkedin.com/in/parulsingh,NaN,https://twitter.com/parulia,raizer.app

In [57]:
copy_data.describe()

,Picture,Website,City,County,Country,Organization Name,Individual Name,Role,Name of Firm,Firm Data Logo,Funding Stage,Industry Focus,Type,Email Id,Phone Number,LinkedIn Profile URL,Facebook Profile URL,Twitter Profile URL,Source of Data
count,6170,51830,80980,58187,101583,0,102995,102995,45316,43730,89182,88373,102995,24092,5929,85922,7851,16404,102995
unique,3977,13022,3102,690,163,0,63549,19,8750,8289,396,22140,219,15183,3252,54478,5034,10434,1
top,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,www.harbourvest.com,New York,California,United States,NaN,Brian Kelly,Angel Investor,HarbourVest Partners,https://xubs-akpz-sxip.n7.xano.io/vault/TEisAJ...,Seed,FinTech,Angel Investor,claire.thielke@gmail.com,9.20E+11,https://www.linkedin.com/in/ken-fredrickson-6a...,http://www.facebook.com/,http://twitter.com/lainetom,raizer.app
freq,6,274,8601,12957,45968,NaN,13,57679,274,274,21485,766,57679,7,127,9,12,7,102995

In [60]:
us_data =copy_data[copy_data['Country']=='United States']

In [61]:
us_data.to_csv('output.csv', index=False)